sml: sml Namespace Reference
sml Namespace Reference
Functions
template<typename Real >
Real computeModulo (const Real dividend, const Real divisor)
Compute modulo.
template<typename Real >
Real convertRadiansToDegrees (const Real angleInRadians)
Convert angle in radians to degrees.
template<typename Real >
Real convertDegreesToRadians (const Real angleInDegrees)
Convert angle in degrees to radians.
template<typename Real , typename FunctionData >
Real lagrangeInterpolate (const FunctionData &functionData, const Real x)
Compute Lagrange interpolation.
template<typename Vector3 >
Vector3 cross (const Vector3 &vector1, const Vector3 &vector2)
Compute cross-product of two 3-vectors.
template<typename Real , typename Vector >
Real dot (const Vector &vector1, const Vector &vector2)
Compute dot-product of two equal-length vectors.
template<typename Real , typename Vector >
Real squaredNorm (const Vector &vector)
Compute squared-norm of vector.
template<typename Real , typename Vector >
Real norm (const Vector &vector)
Compute norm of vector.
template<typename Real , typename Vector >
Vector normalize (const Vector &vector)
Normalize vector.
template<typename Vector3 >
Vector3 getXUnitVector ()
Get unit-vector in x-direction.
template<typename Vector3 >
Vector3 getYUnitVector ()
Get unit-vector in y-direction.
template<typename Vector3 >
Vector3 getZUnitVector ()
Get unit-vector in z-direction.
template<typename Real , typename Vector >
Vector multiply (const Vector &vector, const Real multiplier)
Multiply by scalar element-wise.
template<typename Real , typename Vector >
Vector add (const Vector &vector, const Real adder)
Add scalar element-wise.
template<typename Vector >
Vector add (const Vector &vector1, const Vector &vector2)
Add two vectors element-wise.
Variables
static const double SML_PI = 3.14159265358979323846
to 20 decimal places.
Function Documentation
computeModulo()
template<typename Real > Real sml::computeModulo (const Real dividend, const Real divisor)
Computes the remainder of division of one real number by another. The remainder is in the range [0, divisor).
The modulo computation is based on the mathematical definition of congruence, which is different from the implementation of std::fmod() in the cmath standard library.
For a description of congruence see: http://mathworld.wolfram.com/Congruence.html.
Template Parameters
Real Real type
Parameters
dividend Number to be divided.
divisor Number that divides dividend
Returns
Remainder of division of dividend by divisor
Definition at line 32 of file basicFunctions.hpp.
convertRadiansToDegrees()
template<typename Real > Real sml::convertRadiansToDegrees (const Real angleInRadians)
Converts angle given in radians to degrees using the following equation:
Template Parameters
Real Real type
Parameters
angleInRadians Angle in radians
Returns
Angle in degrees
Definition at line 50 of file basicFunctions.hpp.
References SML_PI.
convertDegreesToRadians()
template<typename Real > Real sml::convertDegreesToRadians (const Real angleInDegrees)
Converts angle given in degrees to radians using the following equation:
Template Parameters
Real Real type
Parameters
angleInDegrees Angle in degrees
Returns
Angle in radians
Definition at line 68 of file basicFunctions.hpp.
References SML_PI.
lagrangeInterpolate()
template<typename Real , typename FunctionData > Real sml::lagrangeInterpolate (const FunctionData & functionData, const Real x)
Computes Lagrange interpolation polynomial to obtain y-value for a specified x value, given a function described by a collection of N non-evenly distributed (x,y) pairs.
Note that this implementation doesn't account for interpolation at boundaries. For the best results, the x-value to interpolate at should be in the center of the x-data.
See Wolfram MathWorld for more background information: https://mathworld.wolfram.com/LagrangeInterpolatingPolynomial.html
Template Parameters
Real Floating-point type
FunctionData Container type with (x,y) pairs describing function
Parameters
functionData A collection of N (x,y) pairs to describe a function
x x-value to interpolate at
Returns
Interpolated y-value
Definition at line 32 of file lagrangeInterpolator.hpp.
cross()
template<typename Vector3 > Vector3 sml::cross (const Vector3 & vector1, const Vector3 & vector2)
Computes the cross-product of two 3-vectors. The cross-product is computed as follows:
Note that the Vector3 type must support the following operation/functions:
[] (element access operator, returning floating-point number)
= (equals operator)
.size() (vector length function)
Template Parameters
Vector3 3-Vector type
Parameters
vector1 A 3-vector
vector2 A 3-vector
Returns
Vector resulting from cross-product
Definition at line 39 of file linearAlgebra.hpp.
dot()
template<typename Real , typename Vector > Real sml::dot (const Vector & vector1, const Vector & vector2)
Computes the dot-product (inner-product) of two vectors of length N. The dot-product is computed as follows:
Note that the Vector type must support the following operation/functions:
[] (element access operator, returning floating-point number)
.size() (vector length function)
Template Parameters
Real Real type
Vector Vector type
Parameters
vector1 A vector of length N
vector2 A vector of length N
Returns
Scalar resulting from dot-product
Definition at line 69 of file linearAlgebra.hpp.
Referenced by squaredNorm().
squaredNorm()
template<typename Real , typename Vector > Real sml::squaredNorm (const Vector & vector)
Computes the square of the Euclidean norm of a vector of length N. This is computed as the dot-product of the vector with itself. The squared-norm of vector is computed as follows:
Note that the Vector type must support the following operation/functions:
[] (element access operator, returning floating-point number)
.size() (vector length function)
See also
dot
Template Parameters
Real Real type
Vector Vector type
Parameters
vector A vector of length N
Returns
Scalar squared-norm of vector
Definition at line 101 of file linearAlgebra.hpp.
References dot().
Referenced by norm().
norm()
template<typename Real , typename Vector > Real sml::norm (const Vector & vector)
Computes the Euclidean norm of a vector of length N. This is computed as the square-root of the dot-product of the vector with itself. The norm of vector is computed as follows:
Note that the Vector type must support the following operation/functions:
[] (element access operator, returning floating-point number)
.size() (vector length function)
See also
squaredNorm, dot
Template Parameters
Real Real type
Vector Vector type
Parameters
vector A vector of length N
Returns
Scalar norm of vector
Definition at line 127 of file linearAlgebra.hpp.
References squaredNorm().
Referenced by normalize().
normalize()
template<typename Real , typename Vector > Vector sml::normalize (const Vector & vector)
Normalizes a vector of length N by computing the Euclidean norm of the vector and dividing by the norm component-wise. The result is a unit-vector. A vector is normalized as follows:
Note that the Vector type must support the following operation/functions:
[] (element access operator, returning floating-point number)
.size() (vector length function)
See also
norm, dot
Template Parameters
Real Real type
Vector Vector type
Parameters
vector A vector of length N
Returns
Normalized vector
Definition at line 154 of file linearAlgebra.hpp.
References norm().
getXUnitVector()
template<typename Vector3 > Vector3 sml::getXUnitVector ()
Returns unit-vector in the x-direction as column vector.
Note that the Vector type must support the following operation/functions:
constructor to create object with array of specified length
[] (element access operator, returning floating-point number)
Template Parameters
Vector3 Type for 3-vector
Returns
Unit-vector in x-direction
Definition at line 177 of file linearAlgebra.hpp.
getYUnitVector()
template<typename Vector3 > Vector3 sml::getYUnitVector ()
Returns unit-vector in the y-direction as column vector.
Note that the Vector type must support the following operation/functions:
constructor to create object with array of specified length
[] (element access operator, returning floating-point number)
Template Parameters
Vector3 Type for 3-vector
Returns
Unit-vector in y-direction
Definition at line 198 of file linearAlgebra.hpp.
getZUnitVector()
template<typename Vector3 > Vector3 sml::getZUnitVector ()
Returns unit-vector in the z-direction as column vector.
Note that the Vector type must support the following operation/functions:
constructor to create object with array of specified length
[] (element access operator, returning floating-point number)
Template Parameters
Vector3 Type for 3-vector
Returns
Unit-vector in z-direction
Definition at line 219 of file linearAlgebra.hpp.
multiply()
template<typename Real , typename Vector > Vector sml::multiply (const Vector & vector, const Real multiplier)
Multiply each element of a vector of length N by a scalar.
Note that the Vector type must support the following operation/functions:
copy constructor
[] (element access operator, returning floating-point number)
.size() (vector length function)
Template Parameters
Real Real type
Vector Vector type
Parameters
vector Vector to multiply element-wise
multiplier Multiplier to multiply vector element-wise
Returns
Vector multiplied element-wise
Definition at line 244 of file linearAlgebra.hpp.
add() [1/2]
template<typename Real , typename Vector > Vector sml::add (const Vector & vector, const Real adder)
Add a scalar to each element of a vector of length N.
Note that the Vector type must support the following operation/functions:
copy constructor
[] (element access operator, returning floating-point number)
.size() (vector length function)
Template Parameters
Real Real type
Vector Vector type
Parameters
vector Vector to add to element-wise
adder Added to multiply vector element-wise
Returns
Vector added to element-wise
Definition at line 270 of file linearAlgebra.hpp.
add() [2/2]
template<typename Vector > Vector sml::add (const Vector & vector1, const Vector & vector2)
Add two vectors of length N element-wise.
Note that the Vector type must support the following operation/functions:
copy constructor
[] (element access operator, returning floating-point number)
.size() (vector length function)
Template Parameters
Vector Vector type
Parameters
vector1 A vector to add to element-wise
vector2 A vector to add to element-wise
Returns
Vector resulting from element-wise addition of two vectors
Definition at line 295 of file linearAlgebra.hpp.
Variable Documentation
SML_PI
const double sml::SML_PI = 3.14159265358979323846 static
Definition at line 13 of file constants.hpp.
Referenced by convertDegreesToRadians(), and convertRadiansToDegrees().